import { cookies } from 'next/headers';
import { getServices } from '../../database/services';
import { getUserBySessionToken } from '../../database/users';
import ServiceButton from './ServiceButton';

export const metadata = {
  title: { default: 'Services | Pna academy', template: '%s | Pna academy' },
  description: 'Generated by create next app',
};

export default async function ServicesPage() {
  const cookieStore = cookies();
  const sessionToken = cookieStore.get('sessionToken');

  const user =
    sessionToken && (await getUserBySessionToken(sessionToken.value));
  console.log(user);

  const services = await getServices();
  return (
    <div>
      <h1>YOU CHOOSE HOW YOU WANT TO REACH YOUR GREATNESS.</h1>
      {services.map((service) => (
        <div key={`service-div-${service.id}`}>
          <h2>{service.name}</h2>
          <p>{service.description}</p>
          <p>{service.duration}</p>
          <p>{service.price}$</p>
          {user ? (
            <ServiceButton userId={user.id} serviceId={service.id} />
          ) : (
            ''
          )}

          <hr />
        </div>
      ))}
    </div>
  );
}
